url: 'https://nirds.cs.odu.edu'
baseurl: ''
title: 'NIRDS Lab'
lang: 'en'
future: true
timezone: TIMEZONE

header_pages:
  - team.md
  - research.md
  - publications.md
  - grants.md
  - equipments.md
  - datasets.md
